jenkins file updated

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -1,29 +1,45 @@
 pipeline {
     agent any
+
     stages {
         stage('Clone Repository') {
             steps {
-                git 'https://github.com/your-repo/project-devops.git'
+                git 'https://github.com/your-username/project-devops.git'
             }
         }
+
         stage('Build Docker Image') {
             steps {
-                sh 'docker build -t webapp ./docker'
+                script {
+                    sh 'docker build -t devops-static-site ./docker'
+                }
             }
         }
+
         stage('Run Docker Container') {
             steps {
+                script {
+                    sh 'docker run -d -p 8080:80 --name webapp devops-static-site || true'
+                }
+            }
+        }
+
+        stage('Deploy via Ansible') {
+            steps {
                 sh '''
-                docker stop webapp || true
-                docker rm webapp || true
-                docker run -d -p 8080:80 --name webapp webapp
+                cd ansible
+                ansible-playbook -i hosts playbook.yml
                 '''
             }
         }
-        stage('Deploy with Ansible') {
-            steps {
-                sh 'ansible-playbook -i ansible/hosts ansible/playbook.yml'
-            }
+    }
+
+    post {
+        success {
+            echo 'Deployment successful!'
+        }
+        failure {
+            echo 'Deployment failed.'
         }
     }
 }
